name: miscelaneos
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  dio: ^5.4.2+1
  flutter:
    sdk: flutter
  flutter_compass: ^0.8.0
  flutter_riverpod: ^2.4.10
  go_router: ^13.2.0
  google_fonts: ^6.1.0
  local_auth: ^2.1.8
  permission_handler: ^11.3.0
  sensors_plus: ^4.0.2
  share_plus: ^8.0.2

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/compass/
