name: miscelaneos
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  dio: ^5.4.2+1
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.5.0
  flutter_compass: ^0.8.0
  flutter_riverpod: ^2.4.10
  geolocator: ^11.0.0
  go_router: ^13.2.0
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.6.1
  google_mobile_ads: ^5.0.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  local_auth: ^2.1.8
  path_provider: ^2.1.3
  permission_handler: ^11.3.0
  quick_actions: ^1.0.7
  sensors_plus: ^4.0.2
  share_plus: ^8.0.2
  shared_preferences: ^2.2.3
  workmanager: ^0.5.2

dev_dependencies:
  build_runner: ^2.4.9
  change_app_package_name: ^1.1.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/compass/
